# Generated by Django 2.1.4 on 2019-01-04 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章表'},
        ),
        migrations.AlterModelOptions(
            name='article2tag',
            options={'verbose_name_plural': '文章与标签关系表'},
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'JavaScript'), (4, 'PHP')], default=None),
        ),
        migrations.AlterField(
            model_name='blog',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.UserInfo', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together=set(),
        ),
    ]
