# Generated by Django 2.1.4 on 2019-01-07 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190104_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': '互粉表',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='repository.Blog', verbose_name='所属博客'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_type_id',
            field=models.IntegerField(choices=[(1, 'Python'), (2, 'Linux'), (3, 'JavaScript'), (4, 'PHP')], default=None, verbose_name='主站分类'),
        ),
        migrations.AlterField(
            model_name='article',
            name='detail',
            field=models.CharField(max_length=500, verbose_name='详细'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='summary',
            field=models.CharField(max_length=32, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='surfix',
            field=models.CharField(max_length=32, verbose_name='昵称前缀'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(max_length=32, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=32, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='category',
            name='caption',
            field=models.CharField(max_length=32, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(upload_to='media/upload_imgs'),
        ),
        migrations.AddField(
            model_name='user2user',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromUser', to='repository.UserInfo', verbose_name='被关注者'),
        ),
        migrations.AddField(
            model_name='user2user',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toUser', to='repository.UserInfo', verbose_name='粉丝'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_user',
            field=models.ManyToManyField(through='repository.User2User', to='repository.UserInfo'),
        ),
        migrations.AlterUniqueTogether(
            name='user2user',
            unique_together={('from_user', 'to_user')},
        ),
    ]
