# Generated by Django 2.1.4 on 2019-01-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20190107_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ctime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
